language: objective-c
osx_image: xcode9.0
env: LC_CTYPE=en_US.UTF-8
before_install:
  - bundle install
script:
- bundle exec fastlane ${LANE}
env:
  matrix:
    - LANE='cocoapods_lint'
    - LANE='citest ios:11'
after_success:
  - bash <(curl -s https://codecov.io/bash)